name: Stale branch removal

on:
  workflow_dispatch:

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Stale Branches
        uses: fpicalausa/remove-stale-branches@v2.0.1
        with:
          exempt-branches-regex: "^(main|master|develop)$"
          days-before-branch-stale: 60
          days-before-branch-delete: 7
          dry-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  deployment-notification:
    runs-on: ubuntu-latest
    needs: remove-stale-branches
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: |
            Branch Removal Job Completed
            The branch removal job has completed with status: ${{ needs.remove-stale-branches.result }}.
            Please check the logs for more details.
        if: always()
